export type ActivityType =
  | 'sound_detective' | 'sound_builder' | 'sound_switch'
  | 'word_builder' | 'mystery_words' | 'reading_mission';

export type Activity = {
  id: string; type: ActivityType; skillId: string; title: string;
  instruction: string; prompt: string; audioText?: string; phonemes?: string[];
  choices?: string[]; tokens?: string[]; distractorTokens?: string[]; answer: string;
  manipulation?: 'substitute' | 'delete';
  hint: string; difficulty: number;
};

export const activityBank: Activity[] = [
  {id:'sd1',type:'sound_detective',skillId:'PA-02',title:'Sound Detective',instruction:'Listen first. Find the word that starts with the sound.',prompt:'Which word starts with /sh/?',audioText:'Listen for the sh sound. Shhh.',choices:['ship','chip','sip'],answer:'ship',hint:'Stretch the beginning: shhh-ip.',difficulty:1},
  {id:'sd2',type:'sound_detective',skillId:'PA-02',title:'Sound Detective',instruction:'Listen first. Find the word that starts with the sound.',prompt:'Which word starts with /ch/?',audioText:'Listen for the ch sound. Ch.',choices:['share','chair','stair'],answer:'chair',hint:'Listen for the quick /ch/ sound at the start.',difficulty:1},
  {id:'sd3',type:'sound_detective',skillId:'PA-03',title:'Sound Detective',instruction:'Listen for the middle sound.',prompt:'Which word has /ă/ in the middle?',audioText:'Listen for the short a sound, like the middle sound in apple.',choices:['map','mop','meep'],answer:'map',hint:'Stretch each word and listen only to the middle.',difficulty:2},
  {id:'sd4',type:'sound_detective',skillId:'PA-03',title:'Sound Detective',instruction:'Listen for the middle sound.',prompt:'Which word has /ĭ/ in the middle?',audioText:'Listen for the short i sound, like the middle sound in sit.',choices:['fish','fash','foosh'],answer:'fish',hint:'Say each slowly. Which middle sound is /ĭ/?',difficulty:2},

  {id:'sb1',type:'sound_builder',skillId:'PA-04',title:'Sound Builder',instruction:'Count the sounds you hear, not the letters.',prompt:'How many sounds are in “phone”?',audioText:'phone',choices:['2 sounds','3 sounds','4 sounds'],answer:'3 sounds',hint:'Say it slowly: /f/ /ō/ /n/.',difficulty:2},
  {id:'sb2',type:'sound_builder',skillId:'PA-04',title:'Sound Builder',instruction:'Count the sounds you hear, not the letters.',prompt:'How many sounds are in “ship”?',audioText:'ship',choices:['2 sounds','3 sounds','4 sounds'],answer:'3 sounds',hint:'/sh/ is one sound. Try /sh/ /ĭ/ /p/.',difficulty:2},
  {id:'sb3',type:'sound_builder',skillId:'PA-04',title:'Sound Builder',instruction:'Count every sound in the word.',prompt:'How many sounds are in “stamp”?',audioText:'stamp',choices:['3 sounds','4 sounds','5 sounds'],answer:'5 sounds',hint:'Stretch it: /s/ /t/ /ă/ /m/ /p/.',difficulty:3},
  {id:'sb4',type:'sound_builder',skillId:'PA-04',title:'Sound Builder',instruction:'Count every sound in the word.',prompt:'How many sounds are in “brush”?',audioText:'brush',choices:['3 sounds','4 sounds','5 sounds'],answer:'4 sounds',hint:'Stretch it: /b/ /r/ /ŭ/ /sh/.',difficulty:3},

  {id:'ss1',type:'sound_switch',skillId:'PA-06',title:'Sound Switch',instruction:'Listen first. Change the sound in your head.',prompt:'Change the first sound in the word you hear to /ch/. What new word do you make?',audioText:'ship',choices:['chip','chin','chat'],answer:'chip',hint:'Hold /ip/ in your head. Replace only the first sound /sh/ with /ch/.',difficulty:2,manipulation:'substitute'},
  {id:'ss2',type:'sound_switch',skillId:'PA-06',title:'Sound Switch',instruction:'Listen first. Change the sound in your head.',prompt:'Change the first sound in the word you hear to /t/. What new word do you make?',audioText:'map',choices:['tap','tan','tag'],answer:'tap',hint:'Hold /ap/ in your head. Replace only /m/ with /t/.',difficulty:2,manipulation:'substitute'},
  {id:'ss3',type:'sound_switch',skillId:'PA-05',title:'Sound Switch',instruction:'Listen first. Take one sound away in your head.',prompt:'Take away /s/ from the word you hear. What word is left?',audioText:'snap',choices:['nap','nab','nat'],answer:'nap',hint:'Hold /s/ /n/ /ă/ /p/ in your head. Remove only the first /s/.',difficulty:3,manipulation:'delete'},
  {id:'ss4',type:'sound_switch',skillId:'PA-05',title:'Sound Switch',instruction:'Listen first. Take one sound away in your head.',prompt:'Take away /s/ from the word you hear. What word is left?',audioText:'fist',choices:['fit','fin','fib'],answer:'fit',hint:'Hold /f/ /ĭ/ /s/ /t/ in your head. Remove /s/ but keep the final /t/.',difficulty:3,manipulation:'delete'},
  {id:'ss5',type:'sound_switch',skillId:'PA-06',title:'Sound Switch',instruction:'Listen first. Change a sound inside the blend.',prompt:'Change /l/ in the word you hear to /k/. What new word do you make?',audioText:'slip',choices:['skip','skit','skim'],answer:'skip',hint:'Keep /s/ at the beginning and /ip/ at the end. Change only /l/ to /k/.',difficulty:4,manipulation:'substitute'},
  {id:'ss6',type:'sound_switch',skillId:'PA-05',title:'Sound Switch',instruction:'Listen first. Take a sound out of the blend.',prompt:'Take away /r/ from the word you hear. What word is left?',audioText:'crash',choices:['cash','cap','cab'],answer:'cash',hint:'Start with /k/ /r/ /ă/ /sh/. Remove only /r/, then blend what remains.',difficulty:4,manipulation:'delete'},
  {id:'ss7',type:'sound_switch',skillId:'PA-05',title:'Sound Switch',instruction:'Listen first. Take a sound out of the blend.',prompt:'Take away /t/ from the word you hear. What mystery word is left?',audioText:'stamp',choices:['samp','sam','sap'],answer:'samp',hint:'Hold /s/ /t/ /ă/ /m/ /p/. Remove only /t/ and keep every other sound.',difficulty:5,manipulation:'delete'},
  {id:'ss8',type:'sound_switch',skillId:'PA-05',title:'Sound Switch',instruction:'Listen first. Take away a sound from a longer word.',prompt:'Take away /t/ from the word you hear. What word is left?',audioText:'winter',choices:['winner','winder','winter'],answer:'winner',hint:'Say winter slowly. Remove the /t/ sound and blend the remaining sounds.',difficulty:5,manipulation:'delete'},

  {id:'wb1',type:'word_builder',skillId:'DC-02',title:'Word Builder',instruction:'Listen to the word. Build it from left to right.',prompt:'Build the word you hear.',audioText:'ship',tokens:['sh','i','p'],answer:'ship',hint:'Say the sounds slowly: /sh/ /ĭ/ /p/. Which sound comes first?',difficulty:2},
  {id:'wb2',type:'word_builder',skillId:'DC-02',title:'Word Builder',instruction:'Listen to the word. Build it from left to right.',prompt:'Build the word you hear.',audioText:'chat',tokens:['ch','a','t'],answer:'chat',hint:'Say the sounds slowly: /ch/ /ă/ /t/. Which sound comes first?',difficulty:2},
  {id:'wb3',type:'word_builder',skillId:'DC-03',title:'Word Builder',instruction:'Listen to the word. Build it from left to right.',prompt:'Build the word you hear.',audioText:'stop',tokens:['s','t','o','p'],distractorTokens:['a'],answer:'stop',hint:'Stretch the beginning blend: /s/ /t/. Then listen for the middle vowel.',difficulty:3},
  {id:'wb4',type:'word_builder',skillId:'DC-03',title:'Word Builder',instruction:'Listen to the word. Build it from left to right.',prompt:'Build the word you hear.',audioText:'brush',tokens:['b','r','u','sh'],distractorTokens:['a'],answer:'brush',hint:'Stretch it: /b/ /r/ /ŭ/ /sh/. Keep both sounds in the beginning blend.',difficulty:3},

  {id:'mw1',type:'mystery_words',skillId:'DC-03',title:'Mystery Words',instruction:'Listen first. Blend the sounds in your head.',prompt:'Blend the sounds. What mystery word do they make?',audioText:'shap',phonemes:['sh','short_a','p'],choices:['shap','sham','shad'],answer:'shap',hint:'Listen again. Keep the beginning and middle sounds the same, then listen closely to the last sound.',difficulty:2},
  {id:'mw2',type:'mystery_words',skillId:'DC-03',title:'Mystery Words',instruction:'Listen first. Blend the sounds in your head.',prompt:'Blend the sounds. What mystery word do they make?',audioText:'chim',phonemes:['ch','short_i','m'],choices:['chim','chip','chit'],answer:'chim',hint:'Listen again. The choices start the same, so focus on the final sound.',difficulty:2},
  {id:'mw3',type:'mystery_words',skillId:'DC-03',title:'Mystery Words',instruction:'Listen first. Hold every sound in the blend.',prompt:'Blend the sounds. What mystery word do they make?',audioText:'slop',phonemes:['s','l','short_o','p'],choices:['slop','slot','slom'],answer:'slop',hint:'Keep /s/ and /l/ together, then listen carefully to the ending sound.',difficulty:3},
  {id:'mw4',type:'mystery_words',skillId:'DC-03',title:'Mystery Words',instruction:'Listen first. Hold every sound in the blend.',prompt:'Blend the sounds. What mystery word do they make?',audioText:'brip',phonemes:['b','r','short_i','p'],choices:['brip','brim','brin'],answer:'brip',hint:'All three begin the same. Listen closely to the very last sound.',difficulty:3},

  {id:'rm1',type:'reading_mission',skillId:'FL-01',title:'Reading Mission',instruction:'Read the mission, then answer.',prompt:'Mia saw a ship at the dock. The ship had a red flag and a tall mast. She sat on a bench with her dad and watched the ship glide past. A small tug boat followed behind it. Mia waved as the ship moved toward the bridge. What did Mia watch glide past?',choices:['a ship','a train','a fish'],answer:'a ship',hint:'Look for what moved past Mia near the dock.',difficulty:2},
  {id:'rm2',type:'reading_mission',skillId:'FL-01',title:'Reading Mission',instruction:'Read the mission, then answer.',prompt:'Ben packed a snack and went on a short hike with his aunt. The path went past a pond and up a small hill. At the top, Ben spotted a red fox near a log. The fox stood still for a moment and then ran into the brush. What animal did Ben see?',choices:['a fox','a frog','a dog'],answer:'a fox',hint:'Look at what Ben spotted near the log.',difficulty:2},
  {id:'rm3',type:'reading_mission',skillId:'FL-02',title:'Reading Mission',instruction:'Read smoothly and use the details to answer.',prompt:'Lena and Max built a small ramp for their toy cars. Max sent a blue car down first, but it stopped on the rug. Lena raised the ramp with two books. This time the car sped across the floor and bumped the wall. What did Lena change?',choices:['She raised the ramp.','She changed the car.','She moved the wall.'],answer:'She raised the ramp.',hint:'What did Lena do with the two books?',difficulty:3},
  {id:'rm4',type:'reading_mission',skillId:'FL-02',title:'Reading Mission',instruction:'Read smoothly and use the details to answer.',prompt:'A storm passed through town before dinner. When the rain stopped, Noah put on his boots and went outside. He found small branches on the grass and a puddle beside the curb. Then the sun came out, and he saw a bright rainbow over the houses. What happened after the rain stopped?',choices:['Noah went outside.','Dinner started.','The storm got stronger.'],answer:'Noah went outside.',hint:'Find the sentence that begins “When the rain stopped.”',difficulty:3}
];

// Kept for compatibility with any Phase 2 imports.
export const lesson = activityBank;
