import type { Activity } from './lesson';

type ReadingQuestion = { prompt:string; choices:string[]; answer:string; hint:string };
type ReadingPassage = {
  id:string; level:string; difficulty:number; skillId:string; pattern:string;
  text:string; questions:ReadingQuestion[];
};

export const readingPassages: ReadingPassage[] = [
  {"id": "rm01", "level": "cvc", "difficulty": 2, "skillId": "FL-01", "pattern": "CVC", "text": "Sam has a red cap. He puts the cap in his bag and runs to the bus. At the bus stop, Sam sees his pal Ben. Ben has a tan hat. Sam and Ben sit next to each other on the bus.", "questions": [{"prompt": "What did Sam put in his bag?", "choices": ["his red cap", "a map", "a snack"], "answer": "his red cap", "hint": "Look at the first two sentences."}, {"prompt": "Who sat next to Sam on the bus?", "choices": ["Ben", "Dad", "Max"], "answer": "Ben", "hint": "Look at the last sentence."}]},
  {"id": "rm02", "level": "cvc", "difficulty": 2, "skillId": "FL-01", "pattern": "CVC", "text": "Mia has a pet cat named Pip. Pip naps on a soft mat by the window. When Mia taps the food dish, Pip gets up and runs to her. Mia gives Pip a bit of food and pats his back.", "questions": [{"prompt": "Where did Pip nap?", "choices": ["on a mat", "in a box", "on a bed"], "answer": "on a mat", "hint": "Look at where Pip was sleeping."}, {"prompt": "What made Pip get up?", "choices": ["Mia tapped the food dish", "the window shut", "a dog ran past"], "answer": "Mia tapped the food dish", "hint": "Find what Mia did just before Pip got up."}]},
  {"id": "rm03", "level": "cvc", "difficulty": 2, "skillId": "FL-01", "pattern": "CVC", "text": "Max and Dad pack a lunch. Max has ham, an apple, and a cup of milk. They sit on a log at the park. A duck swims past them in the pond. Max drops a bit of his napkin, so he picks it up.", "questions": [{"prompt": "Where did Max and Dad eat?", "choices": ["at the park", "at home", "on a bus"], "answer": "at the park", "hint": "Find where they sat on the log."}, {"prompt": "What did Max pick up?", "choices": ["a bit of napkin", "an apple", "a duck"], "answer": "a bit of napkin", "hint": "Look at the last sentence."}]},
  {"id": "rm04", "level": "cvc", "difficulty": 2, "skillId": "FL-01", "pattern": "CVC", "text": "Jen has a big box of blocks. She makes a tall red wall and a small tan hut. Her dog, Gus, bumps the wall with his tail. The wall falls, but Jen just grins and starts again.", "questions": [{"prompt": "What did Jen build with the blocks?", "choices": ["a wall and a hut", "a ship and a dock", "a ramp and a car"], "answer": "a wall and a hut", "hint": "Look at the things Jen made."}, {"prompt": "Why did the wall fall?", "choices": ["Gus bumped it", "Jen kicked it", "the wind hit it"], "answer": "Gus bumped it", "hint": "Find what happened right before the wall fell."}]},
  {"id": "rm05", "level": "cvc", "difficulty": 2, "skillId": "FL-01", "pattern": "CVC", "text": "Tim gets a map from his mom. The map shows a path to a pond. Tim and Mom walk past a big rock and a red shed. At the pond, they sit and watch six ducks swim.", "questions": [{"prompt": "Where did the map lead Tim?", "choices": ["to a pond", "to a shop", "to a hill"], "answer": "to a pond", "hint": "The map shows a path to this place."}, {"prompt": "What did Tim and Mom watch?", "choices": ["ducks", "fish", "dogs"], "answer": "ducks", "hint": "Look at the last sentence."}]},
  {"id": "rm06", "level": "cvc", "difficulty": 2, "skillId": "FL-01", "pattern": "CVC", "text": "Ava sets a pan on the table. She has jam, buns, and cut-up fruit for lunch. Her little brother Ned grabs a bun. Ava laughs and puts jam on one for him.", "questions": [{"prompt": "What did Ned grab?", "choices": ["a bun", "a pan", "a cup"], "answer": "a bun", "hint": "Find what Ned took."}, {"prompt": "What did Ava put on the bun?", "choices": ["jam", "milk", "ham"], "answer": "jam", "hint": "Look at the last sentence."}]},
  {"id": "rm07", "level": "cvc", "difficulty": 2, "skillId": "FL-01", "pattern": "CVC", "text": "Leo and Kim play tag in the yard. Leo runs to the big oak tree. Kim tags him just as he gets to the trunk. Then Leo is it, and Kim runs toward the gate.", "questions": [{"prompt": "What game did Leo and Kim play?", "choices": ["tag", "chess", "catch"], "answer": "tag", "hint": "Look at the first sentence."}, {"prompt": "Who was it after Kim made the tag?", "choices": ["Leo", "Kim", "Dad"], "answer": "Leo", "hint": "Find what happened after Kim tagged Leo."}]},
  {"id": "rm08", "level": "cvc", "difficulty": 2, "skillId": "FL-01", "pattern": "CVC", "text": "Nia fills a tub with warm water. She puts in a red cup and a toy duck. Her little pup tries to grab the duck. Nia lifts the duck out before the pup gets wet.", "questions": [{"prompt": "What two toys did Nia put in the tub?", "choices": ["a cup and a duck", "a ball and a boat", "a fish and a block"], "answer": "a cup and a duck", "hint": "Look at what Nia put into the water."}, {"prompt": "Why did Nia lift out the duck?", "choices": ["the pup tried to grab it", "the water was cold", "the cup sank"], "answer": "the pup tried to grab it", "hint": "Find what the pup did."}]},
  {"id": "rm09", "level": "cvc", "difficulty": 2, "skillId": "FL-01", "pattern": "CVC", "text": "Cal has a kit for a small red jet. He sets each part on a mat. First he adds the wings. Then he adds the tail. At last, Cal puts a star on the side of the jet.", "questions": [{"prompt": "What did Cal add first?", "choices": ["the wings", "the tail", "the star"], "answer": "the wings", "hint": "Look for the word “First.”"}, {"prompt": "Where did Cal put the star?", "choices": ["on the side of the jet", "on the mat", "on the wing tip"], "answer": "on the side of the jet", "hint": "Look at the last sentence."}]},
  {"id": "rm10", "level": "cvc", "difficulty": 2, "skillId": "FL-01", "pattern": "CVC", "text": "Zoe has a bag of seeds. She digs six small spots in the dirt and drops a seed in each one. Then she pats the dirt flat and gets a can of water. Zoe hopes the sun will help the plants grow.", "questions": [{"prompt": "What did Zoe put in the dirt?", "choices": ["seeds", "rocks", "sticks"], "answer": "seeds", "hint": "Look at what Zoe dropped into each spot."}, {"prompt": "What did Zoe get after she patted the dirt?", "choices": ["a can of water", "a red bag", "a rake"], "answer": "a can of water", "hint": "Find what happened next."}]},
  {"id": "rm11", "level": "digraph", "difficulty": 2, "skillId": "FL-01", "pattern": "DIGRAPH", "text": "Mia saw a ship at the dock. The ship had a red flag and a tall mast. She sat on a bench with her dad and watched the ship glide past. A small tug boat followed behind it.", "questions": [{"prompt": "What did Mia watch glide past?", "choices": ["a ship", "a train", "a fish"], "answer": "a ship", "hint": "Look for what moved past Mia."}, {"prompt": "What followed behind the ship?", "choices": ["a tug boat", "a red car", "a duck"], "answer": "a tug boat", "hint": "Look at the last sentence."}]},
  {"id": "rm12", "level": "digraph", "difficulty": 2, "skillId": "FL-01", "pattern": "DIGRAPH", "text": "Chip has a fish tank in his room. He feeds the fish each morning before school. One fish hides by a shell when Chip walks up. When the food drops in, the fish darts out.", "questions": [{"prompt": "Where did the fish hide?", "choices": ["by a shell", "under a chair", "in a dish"], "answer": "by a shell", "hint": "Find the place where the fish hid."}, {"prompt": "What made the fish dart out?", "choices": ["the food dropped in", "Chip shut the door", "the light went off"], "answer": "the food dropped in", "hint": "Look at what happened just before the fish came out."}]},
  {"id": "rm13", "level": "digraph", "difficulty": 2, "skillId": "FL-01", "pattern": "DIGRAPH", "text": "Beth and her dad walk to the shed. They need a thin brush to fix a small scratch on a chair. Beth finds the brush on a shelf. Dad thanks her and starts the job.", "questions": [{"prompt": "What did Beth and Dad need?", "choices": ["a brush", "a shovel", "a dish"], "answer": "a brush", "hint": "Look at what they needed for the scratch."}, {"prompt": "Where did Beth find it?", "choices": ["on a shelf", "under the chair", "in the yard"], "answer": "on a shelf", "hint": "Find where Beth found the brush."}]},
  {"id": "rm14", "level": "digraph", "difficulty": 2, "skillId": "FL-01", "pattern": "DIGRAPH", "text": "Josh takes his lunch to the bench. He has a cheese dish, a peach, and a drink. A gust of wind tips his napkin off the bench. Josh chases it and catches it by a bush.", "questions": [{"prompt": "What blew off the bench?", "choices": ["a napkin", "a peach", "a drink"], "answer": "a napkin", "hint": "Find what the wind moved."}, {"prompt": "Where did Josh catch it?", "choices": ["by a bush", "at the shop", "under a chair"], "answer": "by a bush", "hint": "Look at the last sentence."}]},
  {"id": "rm15", "level": "digraph", "difficulty": 2, "skillId": "FL-01", "pattern": "DIGRAPH", "text": "Chad and Mom shop for a gift. Chad picks a thick book about sharks. Mom finds a bright gift bag. At home, Chad slips the book into the bag and adds a card.", "questions": [{"prompt": "What gift did Chad pick?", "choices": ["a book about sharks", "a toy ship", "a red hat"], "answer": "a book about sharks", "hint": "Look at what Chad chose."}, {"prompt": "What did Chad add after the book?", "choices": ["a card", "a shell", "a snack"], "answer": "a card", "hint": "Look at the last sentence."}]},
  {"id": "rm16", "level": "digraph", "difficulty": 2, "skillId": "FL-01", "pattern": "DIGRAPH", "text": "A small chick gets out of its pen. It runs past the shed and stops by a patch of grass. Liv walks slowly so she will not scare it. She sets down a dish of food, and the chick comes back.", "questions": [{"prompt": "Where did the chick stop?", "choices": ["by a patch of grass", "at the pond", "under a bench"], "answer": "by a patch of grass", "hint": "Find where the chick stopped running."}, {"prompt": "How did Liv get the chick to come back?", "choices": ["she set down food", "she ran after it", "she rang a bell"], "answer": "she set down food", "hint": "Look at what Liv did before the chick returned."}]},
  {"id": "rm17", "level": "digraph", "difficulty": 2, "skillId": "FL-01", "pattern": "DIGRAPH", "text": "Shay has a shell from the beach. She washes it in the sink and sets it on a cloth. When it is dry, she draws the shell in her sketch pad. She shades the dark spots with a gray pencil.", "questions": [{"prompt": "Where did Shay wash the shell?", "choices": ["in the sink", "at the beach", "in a tub"], "answer": "in the sink", "hint": "Look at the second sentence."}, {"prompt": "What did Shay do after the shell was dry?", "choices": ["she drew it", "she threw it", "she washed it again"], "answer": "she drew it", "hint": "Find what happened after it dried."}]},
  {"id": "rm18", "level": "digraph", "difficulty": 2, "skillId": "FL-01", "pattern": "DIGRAPH", "text": "Rich and his sister walk on a path by the marsh. They hear a splash and stop. A frog hops from the mud into the water. Rich points to the spot, but the frog is already gone.", "questions": [{"prompt": "What made Rich and his sister stop?", "choices": ["a splash", "a shout", "a bell"], "answer": "a splash", "hint": "Look at what they heard."}, {"prompt": "What animal jumped into the water?", "choices": ["a frog", "a fish", "a duck"], "answer": "a frog", "hint": "Find what hopped from the mud."}]},
  {"id": "rm19", "level": "digraph", "difficulty": 2, "skillId": "FL-01", "pattern": "DIGRAPH", "text": "Theo puts three shells in a row. The first shell is white, the next is tan, and the last has pink spots. His sister picks the shell with pink spots. Theo keeps the white shell.", "questions": [{"prompt": "Which shell did Theo's sister pick?", "choices": ["the shell with pink spots", "the white shell", "the tan shell"], "answer": "the shell with pink spots", "hint": "Look at which shell his sister chose."}, {"prompt": "Which shell did Theo keep?", "choices": ["the white shell", "the tan shell", "the pink shell"], "answer": "the white shell", "hint": "Look at the last sentence."}]},
  {"id": "rm20", "level": "digraph", "difficulty": 2, "skillId": "FL-01", "pattern": "DIGRAPH", "text": "June helps wash the dishes after lunch. She rinses each dish and hands it to Dad. Dad dries the dishes with a cloth and stacks them on the shelf. When they finish, June wipes the sink.", "questions": [{"prompt": "Who dried the dishes?", "choices": ["Dad", "June", "Mom"], "answer": "Dad", "hint": "Find who used the cloth."}, {"prompt": "What did June do when they finished?", "choices": ["wiped the sink", "made lunch", "washed the shelf"], "answer": "wiped the sink", "hint": "Look at the last sentence."}]},
  {"id": "rm21", "level": "blend", "difficulty": 3, "skillId": "FL-02", "pattern": "BLEND", "text": "Ben packed a snack and went on a short hike with his aunt. The path went past a pond and up a small hill. At the top, Ben spotted a red fox near a log. The fox stood still, then ran into the brush.", "questions": [{"prompt": "What animal did Ben see?", "choices": ["a fox", "a frog", "a dog"], "answer": "a fox", "hint": "Look at what Ben spotted near the log."}, {"prompt": "Where was Ben when he saw the fox?", "choices": ["at the top of the hill", "beside the car", "inside a shop"], "answer": "at the top of the hill", "hint": "Find where Ben was just before he spotted the fox."}]},
  {"id": "rm22", "level": "blend", "difficulty": 3, "skillId": "FL-02", "pattern": "BLEND", "text": "Lena and Max built a small ramp for their toy cars. Max sent a blue car down first, but it stopped on the rug. Lena raised the ramp with two books. This time the car sped across the floor.", "questions": [{"prompt": "What did Lena change?", "choices": ["She raised the ramp.", "She changed the car.", "She moved the rug."], "answer": "She raised the ramp.", "hint": "What did Lena do with the two books?"}, {"prompt": "What happened after Lena raised the ramp?", "choices": ["The car sped across the floor.", "The car stopped on the rug.", "The books fell."], "answer": "The car sped across the floor.", "hint": "Look at the sentence after Lena used the books."}]},
  {"id": "rm23", "level": "blend", "difficulty": 3, "skillId": "FL-02", "pattern": "BLEND", "text": "A storm passed through town before dinner. When the rain stopped, Noah put on his boots and went outside. He found small branches on the grass and a puddle by the curb. Then the sun came out.", "questions": [{"prompt": "What did Noah do after the rain stopped?", "choices": ["He went outside.", "He ate dinner.", "He went to bed."], "answer": "He went outside.", "hint": "Find the sentence that begins “When the rain stopped.”"}, {"prompt": "What did Noah find on the grass?", "choices": ["small branches", "a red flag", "toy cars"], "answer": "small branches", "hint": "Look at what was on the grass."}]},
  {"id": "rm24", "level": "blend", "difficulty": 3, "skillId": "FL-02", "pattern": "BLEND", "text": "Grace plants a small garden behind the shed. She puts spinach in one row and radish seeds in the next. Each morning she checks the soil. If it feels dry, she brings out the hose.", "questions": [{"prompt": "What did Grace plant in the first row?", "choices": ["spinach", "radishes", "grass"], "answer": "spinach", "hint": "Look at the two rows."}, {"prompt": "When does Grace use the hose?", "choices": ["when the soil feels dry", "every night", "when it rains"], "answer": "when the soil feels dry", "hint": "Find what makes her bring out the hose."}]},
  {"id": "rm25", "level": "blend", "difficulty": 3, "skillId": "FL-02", "pattern": "BLEND", "text": "Brent brings a drum to music club. He taps a slow beat while Fran claps along. Then the teacher asks them to try the beat faster. Brent listens, counts to four, and starts again.", "questions": [{"prompt": "What instrument did Brent bring?", "choices": ["a drum", "a flute", "a bell"], "answer": "a drum", "hint": "Look at the first sentence."}, {"prompt": "What did the teacher ask them to change?", "choices": ["the speed of the beat", "the instrument", "the song words"], "answer": "the speed of the beat", "hint": "Find what they were asked to try faster."}]},
  {"id": "rm26", "level": "blend", "difficulty": 3, "skillId": "FL-02", "pattern": "BLEND", "text": "Clara spots a flat stone near the creek. She skips it across the water, and it bounces three times. Her brother tries next, but his stone drops with one splash. Clara shows him how to hold a flat stone.", "questions": [{"prompt": "How many times did Clara's stone bounce?", "choices": ["three times", "one time", "five times"], "answer": "three times", "hint": "Look at the first part of the passage."}, {"prompt": "What did Clara show her brother?", "choices": ["how to hold a flat stone", "how to swim", "how to find the creek"], "answer": "how to hold a flat stone", "hint": "Look at the last sentence."}]},
  {"id": "rm27", "level": "blend", "difficulty": 3, "skillId": "FL-02", "pattern": "BLEND", "text": "Drew helps Grandpa stack split logs by the shed. They make one short row, then start a second row beside it. Dark clouds drift over the yard, so Grandpa covers the wood with a tarp.", "questions": [{"prompt": "What were Drew and Grandpa stacking?", "choices": ["logs", "bricks", "boxes"], "answer": "logs", "hint": "Look at the first sentence."}, {"prompt": "Why did Grandpa cover the wood?", "choices": ["dark clouds came", "the sun was bright", "Drew went inside"], "answer": "dark clouds came", "hint": "Find what happened just before the tarp came out."}]},
  {"id": "rm28", "level": "blend", "difficulty": 3, "skillId": "FL-02", "pattern": "BLEND", "text": "A black crab crawls across the sand near Priya's feet. She steps back and watches it slip under a flat rock. Priya calls her brother over, but the crab stays hidden.", "questions": [{"prompt": "Where did the crab hide?", "choices": ["under a flat rock", "in the water", "under a towel"], "answer": "under a flat rock", "hint": "Find where the crab slipped."}, {"prompt": "Why did Priya call her brother?", "choices": ["to show him the crab", "to ask for a snack", "to go swimming"], "answer": "to show him the crab", "hint": "Use the details about what Priya was watching."}]},
  {"id": "rm29", "level": "blend", "difficulty": 3, "skillId": "FL-02", "pattern": "BLEND", "text": "Frank makes a plan for his model plane. First he clips the wings in place. Next he snaps on the wheels. Before he adds the propeller, he checks the picture on the box.", "questions": [{"prompt": "What did Frank attach first?", "choices": ["the wings", "the wheels", "the propeller"], "answer": "the wings", "hint": "Look for the word “First.”"}, {"prompt": "What did Frank check before adding the propeller?", "choices": ["the picture on the box", "the wheels", "the window"], "answer": "the picture on the box", "hint": "Find what he did right before the propeller."}]},
  {"id": "rm30", "level": "blend", "difficulty": 3, "skillId": "FL-02", "pattern": "BLEND", "text": "Sloane brings a blanket to the grass for a picnic. She spreads it under a tree and sets down a basket. A strong gust flips one corner of the blanket. Sloane places a smooth rock on each corner.", "questions": [{"prompt": "What did the wind do?", "choices": ["flipped a corner of the blanket", "knocked down the tree", "opened the basket"], "answer": "flipped a corner of the blanket", "hint": "Find what the gust changed."}, {"prompt": "How did Sloane keep the blanket down?", "choices": ["She put rocks on the corners.", "She sat on the basket.", "She folded the blanket."], "answer": "She put rocks on the corners.", "hint": "Look at the last sentence."}]},
  {"id": "rm31", "level": "complex", "difficulty": 4, "skillId": "FL-02", "pattern": "CCVC_CVCC", "text": "Mason carries a basket of apples from the garden shed. One apple slips through a gap and rolls down the path. Mason sets the basket down, jogs after the apple, and stops it with his foot before it reaches the street.", "questions": [{"prompt": "Why did Mason run down the path?", "choices": ["to get the rolling apple", "to find the basket", "to reach the shed"], "answer": "to get the rolling apple", "hint": "Find what happened before Mason jogged away."}, {"prompt": "How did Mason stop the apple?", "choices": ["with his foot", "with the basket", "with a stick"], "answer": "with his foot", "hint": "Look near the end of the passage."}]},
  {"id": "rm32", "level": "complex", "difficulty": 4, "skillId": "FL-02", "pattern": "CCVC_CVCC", "text": "Brooke and Trent build a blanket fort in the living room. They stretch one blanket across two chairs and clip the edges in place. When the middle sags, Brooke slides a tall box underneath to lift it.", "questions": [{"prompt": "What held the blanket edges in place?", "choices": ["clips", "books", "pillows"], "answer": "clips", "hint": "Look at how they attached the edges."}, {"prompt": "Why did Brooke put a box under the blanket?", "choices": ["to lift the sagging middle", "to store toys", "to block the door"], "answer": "to lift the sagging middle", "hint": "Find the problem the box solved."}]},
  {"id": "rm33", "level": "complex", "difficulty": 4, "skillId": "FL-02", "pattern": "CCVC_CVCC", "text": "Ava practices a tricky jump-rope pattern on the driveway. At first, the rope catches on her shoes. She slows down and watches when the rope touches the ground. After a few tries, she clears the rope five times in a row.", "questions": [{"prompt": "What problem did Ava have at first?", "choices": ["the rope caught on her shoes", "the rope broke", "it started to rain"], "answer": "the rope caught on her shoes", "hint": "Look at what happened at first."}, {"prompt": "What helped Ava improve?", "choices": ["she slowed down and watched the rope", "she got new shoes", "she stopped practicing"], "answer": "she slowed down and watched the rope", "hint": "Find what she changed before she succeeded."}]},
  {"id": "rm34", "level": "complex", "difficulty": 4, "skillId": "FL-02", "pattern": "CCVC_CVCC", "text": "Caleb and his sister collect sticks after a windy night. They drag the largest branch to a pile near the fence. Smaller sticks go into a yard bin. When the grass is clear, they check the path for anything they missed.", "questions": [{"prompt": "Where did they put the largest branch?", "choices": ["near the fence", "in the yard bin", "on the path"], "answer": "near the fence", "hint": "Look at where the largest branch went."}, {"prompt": "What did they do after the grass was clear?", "choices": ["checked the path", "went to sleep", "moved the fence"], "answer": "checked the path", "hint": "Look at the last sentence."}]},
  {"id": "rm35", "level": "complex", "difficulty": 4, "skillId": "FL-02", "pattern": "CCVC_CVCC", "text": "Nora brings a sketch pad on a trip to the pond. She draws a cluster of reeds, a duck, and the reflection of a cloud. A breeze ripples the water, so the reflection changes shape before she can finish it.", "questions": [{"prompt": "What changed before Nora could finish drawing?", "choices": ["the cloud's reflection", "the duck", "the reeds"], "answer": "the cloud's reflection", "hint": "Find what the breeze changed."}, {"prompt": "What caused the change?", "choices": ["a breeze rippled the water", "the duck flew away", "Nora moved the pad"], "answer": "a breeze rippled the water", "hint": "Look at what happened to the water."}]},
  {"id": "rm36", "level": "complex", "difficulty": 4, "skillId": "FL-02", "pattern": "CCVC_CVCC", "text": "Eli helps fix a loose shelf in the garage. He holds the shelf straight while Mom tightens two screws. They place three light boxes on it first to test it. When the shelf stays firm, they add the heavier toolbox.", "questions": [{"prompt": "Why did they put light boxes on the shelf first?", "choices": ["to test the shelf", "to clean the boxes", "to reach the screws"], "answer": "to test the shelf", "hint": "Think about why they waited before adding the heavy box."}, {"prompt": "What did they add after the shelf stayed firm?", "choices": ["the toolbox", "another shelf", "a chair"], "answer": "the toolbox", "hint": "Look at the last sentence."}]},
  {"id": "rm37", "level": "complex", "difficulty": 4, "skillId": "FL-02", "pattern": "CCVC_CVCC", "text": "Harper notices that the plant by her window is leaning toward the light. She turns the pot so the other side faces the window. Over the next few days, the stem begins to grow straighter.", "questions": [{"prompt": "Why did Harper turn the pot?", "choices": ["the plant leaned toward the light", "the soil was wet", "the pot was cracked"], "answer": "the plant leaned toward the light", "hint": "Find what Harper noticed first."}, {"prompt": "What happened over the next few days?", "choices": ["the stem grew straighter", "the plant lost its leaves", "the window closed"], "answer": "the stem grew straighter", "hint": "Look at the last sentence."}]},
  {"id": "rm38", "level": "complex", "difficulty": 4, "skillId": "FL-02", "pattern": "CCVC_CVCC", "text": "Miles and Quinn make a trail of clues for a backyard hunt. The first clue points to the steps. The clue there sends players to the swing. The final note is tucked beneath a flowerpot beside the porch.", "questions": [{"prompt": "Where did the first clue send players?", "choices": ["to the steps", "to the swing", "to the porch"], "answer": "to the steps", "hint": "Look at the first clue."}, {"prompt": "Where was the final note?", "choices": ["beneath a flowerpot", "under the swing", "inside the house"], "answer": "beneath a flowerpot", "hint": "Look at the last sentence."}]},
  {"id": "rm39", "level": "complex", "difficulty": 4, "skillId": "FL-02", "pattern": "CCVC_CVCC", "text": "Sasha hears a strange click from her bike as she rides. She stops and spins the front wheel slowly. A small twig is brushing one of the spokes. Sasha pulls out the twig, spins the wheel again, and the click is gone.", "questions": [{"prompt": "What caused the clicking sound?", "choices": ["a twig touching a spoke", "a flat tire", "a loose seat"], "answer": "a twig touching a spoke", "hint": "Find what Sasha discovered near the wheel."}, {"prompt": "How did Sasha know the problem was fixed?", "choices": ["the click was gone", "the wheel stopped", "the bike fell"], "answer": "the click was gone", "hint": "Look at what happened after she removed the twig."}]},
  {"id": "rm40", "level": "complex", "difficulty": 4, "skillId": "FL-02", "pattern": "CCVC_CVCC", "text": "Jordan packs for a class trip the night before. He checks his list and puts a lunch, a water bottle, and a light jacket in his backpack. In the morning, dark clouds fill the sky, so he adds a small umbrella.", "questions": [{"prompt": "What made Jordan add an umbrella?", "choices": ["dark clouds", "his lunch", "the class list"], "answer": "dark clouds", "hint": "Find what Jordan saw in the morning."}, {"prompt": "When did Jordan pack most of his bag?", "choices": ["the night before", "at school", "after the trip"], "answer": "the night before", "hint": "Look at the first sentence."}]},
];

export type ReadingMissionActivity = Activity & { passageId:string };

export const readingMissionActivities: ReadingMissionActivity[] = readingPassages.flatMap(passage =>
  passage.questions.map((question,index) => ({
    id:`${passage.id}-q${index+1}`,
    passageId:passage.id,
    type:'reading_mission' as const,
    skillId:passage.skillId,
    title:'Reading Mission',
    instruction:'Read the mission, then answer.',
    prompt:`${passage.text} ${question.prompt}`,
    choices:question.choices,
    answer:question.answer,
    hint:question.hint,
    difficulty:passage.difficulty,
    pattern:passage.pattern,
    level:passage.level
  }))
);
